Update outdated ubuntu script samples.
Kudos to Mike Gabriel for this patch!

diff --git a/doc/templates/ubuntu/git-ultrasphinx b/doc/templates/ubuntu/git-ultrasphinx
--- a/doc/templates/ubuntu/git-ultrasphinx
+++ b/doc/templates/ubuntu/git-ultrasphinx
@@ -1,7 +1,7 @@
 #! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          Gitorious Ultrasphinx
-# Required-Start:    
+# Provides:          git-ultrasphinx 
+# Required-Start:    mysql 
 # Required-Stop:     
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
@@ -22,19 +22,23 @@ PID_FILE=$GITORIOUS_HOME/db/sphinx/log/searchd.pid
  
 case "$1" in
   start)
-    /bin/su - git -c "$START_CMD"
+    echo -n "Starting git-ultrasphinx"
+    /bin/su - git -c "$START_CMD" 1>/dev/null 2>/dev/null && echo "." || echo ": FAILURE (already running?)"
     ;;
   stop)
-    /bin/su - git -c "$STOP_CMD"
+    echo -n "Stopping git-ultrasphinx"
+    /bin/su - git -c "$STOP_CMD" 1>/dev/null 2>/dev/null && echo "." || echo ": FAILURE (maybe not running?)"
     ;;
   status)
     /bin/su - git -c "$STATUS_CMD"
     ;;
-        restart)
-    /bin/su - git -c "$RESTART_CMD"
-                ;;
+  restart)
+    echo -n "Restarting git-ultrasphinx"
+    /bin/su - git -c "$RESTART_CMD" 1>/dev/null && echo "."  || echo ": FAILURE"
+    ;;
   *)
     echo $"Usage: $0 {start|stop|restart|status}"
     RETVAL=1
 esac
 exit $RETVAL
+
